[package]
name = "vec-arena"
version = "0.1.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
description = "Object arena resembling Vec<Option<T>>"
documentation = "https://docs.rs/vec-arena"
license = "Apache-2.0/MIT"
readme = "README.md"
