[package]
name = "vec-arena"
version = "0.1.1"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
description = "A simple object arena"
repository = "https://github.com/stjepang/vec-arena"
documentation = "https://docs.rs/vec-arena"
readme = "README.md"
license = "Apache-2.0/MIT"

[dependencies]
unreachable = "0.1"
